[build]
  command = "npm run build"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "22"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888

[[redirects]]
  from = "/portal/admin"
  to = "/portal/admin"
  status = 200
  conditions = { Role = ["admin"] }

[[redirects]]
  from = "/portal/admin"
  to = "/portal/login"
  status = 302
