/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildRouteImport } from './routes/build'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as StudioAccessRouteImport } from './routes/studio-access'
import { Route as CustomerCustomerCodeRouteImport } from './routes/customer/$customerCode'
import { Route as PortalAdminRouteImport } from './routes/portal/admin'
import { Route as PortalClaimsRouteImport } from './routes/portal/claims'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalNfcRouteImport } from './routes/portal/nfc'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalVehiclesRouteImport } from './routes/portal/vehicles'
import { Route as PortalWarrantiesRouteImport } from './routes/portal/warranties'
import { Route as ProjectProjectSlugRouteImport } from './routes/project/$projectSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAccessRoute = StudioAccessRouteImport.update({
  id: '/studio-access',
  path: '/studio-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCustomerCodeRoute = CustomerCustomerCodeRouteImport.update({
  id: '/customer/$customerCode',
  path: '/customer/$customerCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClaimsRoute = PortalClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNfcRoute = PortalNfcRouteImport.update({
  id: '/nfc',
  path: '/nfc',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVehiclesRoute = PortalVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWarrantiesRoute = PortalWarrantiesRouteImport.update({
  id: '/warranties',
  path: '/warranties',
  getParentRoute: () => PortalRoute,
} as any)
const ProjectProjectSlugRoute = ProjectProjectSlugRouteImport.update({
  id: '/project/$projectSlug',
  path: '/project/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/studio-access': typeof StudioAccessRoute
  '/customer/$customerCode': typeof CustomerCustomerCodeRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/claims': typeof PortalClaimsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/nfc': typeof PortalNfcRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/vehicles': typeof PortalVehiclesRoute
  '/portal/warranties': typeof PortalWarrantiesRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/studio-access': typeof StudioAccessRoute
  '/customer/$customerCode': typeof CustomerCustomerCodeRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/claims': typeof PortalClaimsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/nfc': typeof PortalNfcRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/vehicles': typeof PortalVehiclesRoute
  '/portal/warranties': typeof PortalWarrantiesRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/studio-access': typeof StudioAccessRoute
  '/customer/$customerCode': typeof CustomerCustomerCodeRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/claims': typeof PortalClaimsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/nfc': typeof PortalNfcRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/vehicles': typeof PortalVehiclesRoute
  '/portal/warranties': typeof PortalWarrantiesRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/portal'
    | '/projects'
    | '/studio-access'
    | '/customer/$customerCode'
    | '/portal/admin'
    | '/portal/claims'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/nfc'
    | '/portal/profile'
    | '/portal/vehicles'
    | '/portal/warranties'
    | '/project/$projectSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/portal'
    | '/projects'
    | '/studio-access'
    | '/customer/$customerCode'
    | '/portal/admin'
    | '/portal/claims'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/nfc'
    | '/portal/profile'
    | '/portal/vehicles'
    | '/portal/warranties'
    | '/project/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/portal'
    | '/projects'
    | '/studio-access'
    | '/customer/$customerCode'
    | '/portal/admin'
    | '/portal/claims'
    | '/portal/dashboard'
    | '/portal/login'
    | '/portal/nfc'
    | '/portal/profile'
    | '/portal/vehicles'
    | '/portal/warranties'
    | '/project/$projectSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  StudioAccessRoute: typeof StudioAccessRoute
  CustomerCustomerCodeRoute: typeof CustomerCustomerCodeRoute
  ProjectProjectSlugRoute: typeof ProjectProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-access': {
      id: '/studio-access'
      path: '/studio-access'
      fullPath: '/studio-access'
      preLoaderRoute: typeof StudioAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$customerCode': {
      id: '/customer/$customerCode'
      path: '/customer/$customerCode'
      fullPath: '/customer/$customerCode'
      preLoaderRoute: typeof CustomerCustomerCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/claims': {
      id: '/portal/claims'
      path: '/claims'
      fullPath: '/portal/claims'
      preLoaderRoute: typeof PortalClaimsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/nfc': {
      id: '/portal/nfc'
      path: '/nfc'
      fullPath: '/portal/nfc'
      preLoaderRoute: typeof PortalNfcRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/vehicles': {
      id: '/portal/vehicles'
      path: '/vehicles'
      fullPath: '/portal/vehicles'
      preLoaderRoute: typeof PortalVehiclesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/warranties': {
      id: '/portal/warranties'
      path: '/warranties'
      fullPath: '/portal/warranties'
      preLoaderRoute: typeof PortalWarrantiesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/project/$projectSlug': {
      id: '/project/$projectSlug'
      path: '/project/$projectSlug'
      fullPath: '/project/$projectSlug'
      preLoaderRoute: typeof ProjectProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalClaimsRoute: typeof PortalClaimsRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalNfcRoute: typeof PortalNfcRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalVehiclesRoute: typeof PortalVehiclesRoute
  PortalWarrantiesRoute: typeof PortalWarrantiesRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalClaimsRoute: PortalClaimsRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalNfcRoute: PortalNfcRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalVehiclesRoute: PortalVehiclesRoute,
  PortalWarrantiesRoute: PortalWarrantiesRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  PortalRoute: PortalRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  StudioAccessRoute: StudioAccessRoute,
  CustomerCustomerCodeRoute: CustomerCustomerCodeRoute,
  ProjectProjectSlugRoute: ProjectProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
